; auto-generated by filament-profile/regenerate.g - DO NOT EDIT, customize config-override.g / nozzle-<diameter>.g
M98 P"0:/filaments/Luvocom 3F PP CF 9928/config-override.g"
M98 P"0:/sys/meltingplot/filament-profile/apply-nozzle-file.g" S"Luvocom 3F PP CF 9928"
M98 P"0:/sys/meltingplot/filament/on-config.g"
