; This file contains the default DSF configuration for the meltingplot.
; It is included by DSF on startup and can be overridden by a machine specific configuration file (sys/meltingplot/dsf-config-override.g).
; DO NOT EDIT THIS FILE, instead create a dsf-config-override.g file in the sys/meltingplot/ directory and add your custom configuration there.

M586 C'*' ; allow CORS requests from any domain - needed for access through reverse proxy

M98 P"sys/meltingplot/dsf-config-override.g" ; include the machine specific DSF configuration