; This file contains the default DSF configuration for the meltingplot.
; It is included by DSF on startup. DO NOT EDIT THIS FILE - machine specific DSF
; configuration (network, ...) belongs in sys/overrides/dsf-config-override.g.

; move the machine-owned files of a pre-3.7 configuration into sys/overrides/ and
; sys/generated/ before anything reads them (idempotent, see the macro)
M98 P"0:/sys/meltingplot/migrate_overrides.g"

M586 C'*' ; allow CORS requests from any domain - needed for access through reverse proxy

M98 P"0:/sys/overrides/dsf-config-override.g" ; include the machine specific DSF configuration

; Printer name, owned by the machine: written by the image (mp-dsf-seed, mp-set-printer-name),
; never by a config update. Loaded last so it wins over any M550 above; the hostname is
; derived from the same file, which DuetControlServer requires.
if fileexists("0:/sys/overrides/printer-name.g")
  M98 P"0:/sys/overrides/printer-name.g"
