; auto-generated by filament-profile/regenerate.g - DO NOT EDIT, customize config-override.g / nozzle-<diameter>.g
M98 P"0:/filaments/Greentec Pro 1.2mm/config-override.g"
M98 P"0:/sys/meltingplot/filament-profile/apply-nozzle-file.g" S"Greentec Pro 1.2mm"
M98 P"0:/sys/meltingplot/filament/on-config.g"
