; regenerate_filament_config.g
; Rewrites filaments/<S>/config.g as machine-owned boilerplate (override include +
; deferred-load hook). User customizations live in config-override.g; if that file
; is missing, the existing config.g is renamed to config-override.g first, which
; auto-migrates foreign/DWC-created profiles on first use.
; Called from tpost0.g and macros/meltingplot/maintenance/repair-filament-profile
; (blocking-capable contexts only - never call this from daemon.g).
;   M98 P"0:/sys/meltingplot/regenerate_filament_config.g" S"<filament name>"

if global.debug
  echo "regenerate_filament_config.g"

if !exists(param.S)
  M99
if param.S == ""
  M99

if !fileexists("0:/filaments/" ^ param.S ^ "/config-override.g")
  if fileexists("0:/filaments/" ^ param.S ^ "/config.g")
    M471 S{"0:/filaments/" ^ param.S ^ "/config.g"} T{"0:/filaments/" ^ param.S ^ "/config-override.g"}
  else
    echo >{"0:/filaments/" ^ param.S ^ "/config-override.g"} "; " ^ param.S ^ " - user customizations (M572 pressure advance, M207 retract, ...)"

echo >{"0:/filaments/" ^ param.S ^ "/config.g"} "; auto-generated by regenerate_filament_config.g - DO NOT EDIT, customize config-override.g instead"
echo >>{"0:/filaments/" ^ param.S ^ "/config.g"} "M98 P""0:/filaments/" ^ param.S ^ "/config-override.g"""
echo >>{"0:/filaments/" ^ param.S ^ "/config.g"} "M98 P""0:/sys/meltingplot/load_filament_sensorless_conditionally.g"""
