; regenerate_filament_config.g
; Rewrites the machine-owned files of filaments/<S>/:
; - config.g: override include + deferred-load hook. User customizations live in
;   config-override.g; if that file is missing, the existing config.g is renamed
;   to config-override.g first, which auto-migrates foreign/DWC-created profiles.
; - load.g/unload.g: single call to the shared filament_load.g/filament_unload.g
;   with the profile name (F). Only generated once temps.g exists (RRF cannot
;   read temperatures back out of existing G-code files) - temps.g ships with the
;   repo or is written by macro repair-filament-profile.
; Called from tpost0.g and macros/meltingplot/maintenance/repair-filament-profile
; (blocking-capable contexts only - never call this from daemon.g).
;   M98 P"0:/sys/meltingplot/regenerate_filament_config.g" S"<filament name>"

if global.debug
  echo "regenerate_filament_config.g"

if !exists(param.S)
  M99
if param.S == ""
  M99

if !fileexists("0:/filaments/" ^ param.S ^ "/config-override.g")
  if fileexists("0:/filaments/" ^ param.S ^ "/config.g")
    M471 S{"0:/filaments/" ^ param.S ^ "/config.g"} T{"0:/filaments/" ^ param.S ^ "/config-override.g"}
  else
    echo >{"0:/filaments/" ^ param.S ^ "/config-override.g"} "; " ^ param.S ^ " - user customizations (M572 pressure advance, M207 retract, ...)"

echo >{"0:/filaments/" ^ param.S ^ "/config.g"} "; auto-generated by regenerate_filament_config.g - DO NOT EDIT, customize config-override.g / nozzle-<diameter>.g"
echo >>{"0:/filaments/" ^ param.S ^ "/config.g"} "M98 P""0:/filaments/" ^ param.S ^ "/config-override.g"""
echo >>{"0:/filaments/" ^ param.S ^ "/config.g"} "var t = max(state.currentTool, 0)"
echo >>{"0:/filaments/" ^ param.S ^ "/config.g"} "var key = take("""" ^ (round(global.nozzle_diameter[var.t] * 100) / 100), 4)"
echo >>{"0:/filaments/" ^ param.S ^ "/config.g"} "var nozzle = ""0:/filaments/" ^ param.S ^ "/nozzle-"" ^ var.key ^ "".g"""
echo >>{"0:/filaments/" ^ param.S ^ "/config.g"} "if fileexists(var.nozzle)"
echo >>{"0:/filaments/" ^ param.S ^ "/config.g"} "  M98 P{var.nozzle}"
echo >>{"0:/filaments/" ^ param.S ^ "/config.g"} "M98 P""0:/sys/meltingplot/load_filament_sensorless_conditionally.g"""

if fileexists("0:/filaments/" ^ param.S ^ "/temps.g")
  echo >{"0:/filaments/" ^ param.S ^ "/load.g"} "; auto-generated by regenerate_filament_config.g - DO NOT EDIT (temperatures: temps.g, other parameters: config-override.g)"
  echo >>{"0:/filaments/" ^ param.S ^ "/load.g"} "M98 P""0:/sys/meltingplot/filament_load.g"" F""" ^ param.S ^ """"
  echo >{"0:/filaments/" ^ param.S ^ "/unload.g"} "; auto-generated by regenerate_filament_config.g - DO NOT EDIT (temperatures: temps.g, other parameters: config-override.g)"
  echo >>{"0:/filaments/" ^ param.S ^ "/unload.g"} "M98 P""0:/sys/meltingplot/filament_unload.g"" F""" ^ param.S ^ """"
