; auto-generated by filament-profile/regenerate.g - DO NOT EDIT, customize config-override.g / nozzle-<diameter>.g
M98 P"0:/filaments/NOVAMID-1030-CF10 0.4mm/config-override.g"
M98 P"0:/sys/meltingplot/filament-profile/apply-nozzle-file.g" S"NOVAMID-1030-CF10 0.4mm"
M98 P"0:/sys/meltingplot/filament/on-config.g"
