; auto-generated by regenerate_filament_config.g - DO NOT EDIT, customize config-override.g / nozzle-<diameter>.g
M98 P"0:/filaments/ABS/config-override.g"
M98 P"0:/sys/meltingplot/load_nozzle_config.g" S"ABS"
M98 P"0:/sys/meltingplot/load_filament_sensorless_conditionally.g"
